### ISSUE TITLE
Persist installed applications and extensions?

### ISSUE THREAD

**Issue by Gymnae** [ConSol/docker-headless-vnc-container#100]
**Image**
ubuntu-xfce-novnc

**Tag**
latest 

**Short summary**
Besides creating my own dockerfile extending your image to install applications on image creation, is there a way to persists updates, additionally installed apps and extensions?

**Detailed question**
I'm already persisting with a docker volume for ` /headless` , but I'd like to know if I can persist more changes than just the user folder even when I re-created the container or update the image, without resorting to a new dockerfile.

**Comment by s1hofmann** [comment]
The same way you're using a volume for the containers home folder `/headless` you could as well use a volume to persist e.g. `/usr/`. Assuming most&trade; applications will be installed to `/usr/`, this will provide you with persistent installs.
