### ISSUE TITLE
How to run multiple vnc desktop containers on different ports, same machine?

### ISSUE THREAD

**Issue by lddd** [ConSol/docker-headless-vnc-container#101]
Hello there,

how can i have two such constainers running? Starting a new constainer and change ports works but i can´t connect (connection refused). No Firewall.

docker run -d -p 5901:5901 -p 6901:6901 consol/ubuntu-xfce-vnc -> works
docker run -d -p 5902:5902 -p 6902:6902 consol/ubuntu-xfce-vnc -> works not

thanks for your help in advance

**Comment by s1hofmann** [comment]
`docker run -d -p 5902:5902 -p 6902:6902 consol/ubuntu-xfce-vnc`

This way you're mapping ports `5902` and `6902` on your host to container ports `5902` and `6902`.
However, the VNC session is always running on container ports `5901` and `6901`, so you just have to change your port config to map from e.g. host port `6902` to container port `6901`.

```
docker run -d -p 5901:5901 -p 6901:6901 consol/ubuntu-xfce-vnc
docker run -d -p 5902:5901 -p 6902:6901 consol/ubuntu-xfce-vnc
```
