### ISSUE TITLE
Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by thekhieu** [ConSol/docker-headless-vnc-container#106]
**Image**

**Tag**

**Short summary**

**Detailed question**
I was trying install MySQL on container. Can you solve it?

**Comment by s1hofmann** [comment]
Hi @thekhieu!

`I was trying install MySQL on container. Can you solve it?`

What exactly have you been trying?

**Comment by s1hofmann** [comment]
Due to inactivity, I'll close this issue.
