### ISSUE TITLE
How to remote resizing by default

### ISSUE THREAD

**Issue by matdrapeau** [ConSol/docker-headless-vnc-container#107]
How can we set the noVNC option 'remote resizing' by default?
Also how to skip asking for a vnc password by default?

**Comment by s1hofmann** [comment]
Do you want to skip the password at all, or are you trying to pass the password on connect?

I'll have a look at the 'remote resizing' option.

**Comment by s1hofmann** [comment]
Hi @matdrapeau,

any update regarding my question?

**Comment by bbakermmc** [comment]
@s1hofmann How do you set remote resizing in unraid?

**Comment by s1hofmann** [comment]
Due to inactivity, I'll close this issue.

**Comment by matdrapeau** [comment]
@s1hofmann yes I am trying to skip the password, not requiring to input a password in the input box neither as url query parameter
