### ISSUE TITLE
Use dockerfile build image does not work

### ISSUE THREAD

**Issue by 644262163** [ConSol/docker-headless-vnc-container#108]
I am using Dockerfile.centos.xfce.vnc to build the image
Access port 6901 after running
Show
Something went wrong, connection is closed

**Comment by s1hofmann** [comment]
Doing a fresh build results in a newer build of TigerVNC (Xvnc TigerVNC 1.8.0 - built Apr 11 2018 06:06:57 in consol/centos-xfce-vnc:latest vs. Xvnc TigerVNC 1.8.0 - built Nov  2 2018 19:05:14 in current build). I'll further investigate on this problem, thanks for filing a ticket!

Best regards

Simon

**Comment by s1hofmann** [comment]
@644262163 Could you please check the latest version in `dev` branch?

**Comment by 644262163** [comment]
> @ 644262163您能否查看`dev`分行的最新版本？

It's working now. Thank you.

**Comment by s1hofmann** [comment]
Closed via #112
