### ISSUE TITLE
consol/ubuntu-xfce-vnc "/usr" belong to unknown user 4011

### ISSUE THREAD

**Issue by xrxu** [ConSol/docker-headless-vnc-container#109]
**Image**
      consol/ubuntu-xfce-vnc
**Tag**

**Short overview**
why there is user 4011 exists in the system?

**Detailed error description**

default@cdbbed893aef:/$ ls -la /usr/
total 44
drwxrwxr-x 1 4011 4011 4096 May 16  2017 .
drwxr-xr-x 1 root root 4096 Dec 31 05:46 ..
drwxrwxr-x 1 4011 4011 4096 Oct 29 08:48 bin
drwxr-xr-x 2 root root 4096 Apr 12  2016 games
drwxr-xr-x 1 root root 4096 Oct 29 08:48 include
drwxrwxr-x 1 4011 4011 4096 Oct 29 08:48 lib
drwxrwxr-x 3 4011 4011 4096 May 16  2017 lib64
drwxr-xr-x 1 root root 4096 Oct  5 18:03 local
drwxr-xr-x 1 root root 4096 Oct 29 08:47 sbin
drwxrwxr-x 1 4011 4011 4096 Oct 29 08:48 share
drwxr-xr-x 2 root root 4096 Apr 12  2016 src
default@cdbbed893aef:/$ 

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (custom Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Fixed via ab659375fdde809377b9acbd42409dd01e62de1d
