### ISSUE TITLE
Any ways I can see how many users are connected?

### ISSUE THREAD

**Issue by unisqu** [ConSol/docker-headless-vnc-container#114]
Any ways I can see how many users are connected? just so that i know if there's a hacker or i left my pc on somewhere not closed.

**Comment by s1hofmann** [comment]
Hi @unisqu!

One quick thing which comes to my mind would be to check for `ESTABLISHED` connections on your VNC port via `netstat`.

**Comment by s1hofmann** [comment]
I'll close this issue due to inactivity.
