### ISSUE TITLE
Suggestions for Unraid

### ISSUE THREAD

**Issue by bbakermmc** [ConSol/docker-headless-vnc-container#118]
The apps are out of date, you should be rebuilding this like weekly or something.
Because apps out of date, you cant upgrade either since base user doesnt have permissions.

For unraid should auto map downloads to a mount provided in setup.
Also all user configs should be stored to the unraid app cache.  Pain in ass to reconfigure when docker restarts.  Change docker to run as root, lost all bookmarks etc that I configured.

**Comment by amoltxm** [comment]
My main browser is Firefox so below is the Firefox installation and user configs container locations. You can map it to your host share so Firefox and user configs won't be gone after every updates. With this, you can run the container with root user (--user 0) then update Firefox.
/usr/lib/firefox
/headless/.mozilla/firefox
