### ISSUE TITLE
override password not working

### ISSUE THREAD

**Issue by r1sknt** [ConSol/docker-headless-vnc-container#12]
when try to use -e "VNC_PW=my-new-password" the container stops and exited directly

**Comment by toschneck** [comment]
@r1sknt I will take a look at it, what version did you used?

**Comment by r1sknt** [comment]
@toschneck on ubuntu latest build, but i did not try on centos or any other builds

**Comment by toschneck** [comment]
@r1sknt I just tried it and it works, I run:
```.bash
docker run -it -p 6911:6901 -p 5911:5901 -e "VNC_PW=my-new-password" consol/ubuntu-xfce-vnc bash
```

and connect via: http://localhost:6911/vnc_auto.html?password=my-new-password
or also via VNC.

Maybe you did not have the current latest version on your local docker image storage, you can try:
```.bash
docker pull consol/ubuntu-xfce-vnc
```

Just be aware that VNC will only use internally the first 8 characters for the password, see the log:
```.bash
change vnc password!
Password too long - only the first 8 characters will be used
```

**Comment by r1sknt** [comment]
@toschneck well  i have the latest build and the container runs but when open the page it says "Failed to connect to server (code: 1006)"

**Comment by r1sknt** [comment]
Ops i figured this out, the password need to be from MIN 6 to MAX 8.
