### ISSUE TITLE
Accessing noVNC with https

### ISSUE THREAD

**Issue by Goatoverlordwastaken** [ConSol/docker-headless-vnc-container#122]
Hey, I have a setup which makes traefik redirect the subdomains I add from my cloudflare DNS, so I put the headless-vnc-container on my subdomain as vnc.domain.com
I receive a bad gateway error due to the ssl being rejected on a http connection, I didn't find a https port in the usage of noVNC too, is there a way I can connect over https instead of http

**Comment by salderma** [comment]
Hi @Goatoverlordwastaken, I'm new here and not an expert.  I'm working with Traefik (also new to me), but found that I can make Traefik terminate SSL and proxy to a one of these containers.  I'm not sure if I read you query correctly, but for my experiment I am starting the novnc container with the following labels:
```
traefik.http.routers.novnc-https.entrypoints=websecure
traefik.http.routers.novnc-https.tls=true
traefik.http.routers.novnc-https.rule=Host(`<your subdomain>`)
traefik.http.services.novnc-https.loadbalancer.server.port=6901
traefik.http.services.novnc-https.loadbalancer.server.scheme=http
traefik.http.middlewares.novnc-headers.headers.customrequestheaders.X-Forwarded-Proto=https
```

**Comment by EWouters** [comment]
Did you ever get this to work?

There are some rules [here](https://stackoverflow.com/questions/60253372/how-to-write-this-rule-for-traefik-within-docker-swarm), but it doesn't look solved.

**Comment by amoltxm** [comment]
I am using letsencrypt and have no issue accessing noVNC with https. It is very easy to setup.

**Comment by EWouters** [comment]
> I am using letsencrypt and have no issue accessing noVNC with https. It is very easy to setup.

This issue is about hosting noVNC on a subdomain. Did you get that setup @amoltxm ?

**Comment by amoltxm** [comment]
I am currently using subfolder to access it but no issue when tried with subdomain either.

**Comment by EWouters** [comment]
Can you share your traefik config?

**Comment by amoltxm** [comment]
I am using nginx in letsencrypt not traefik. I will try traefik later. Not promise anything since this will be my first time using traefik.
