### ISSUE TITLE
How to grant the default user super user privilege?

### ISSUE THREAD

**Issue by fywu85** [ConSol/docker-headless-vnc-container#132]
The current default user does not have root permission. How to modify the Dockerfile such that USER 1000 comes by default with sudo privilege without needing a password?

**Comment by plaihonen** [comment]
Why would the default user need sudo privileges?

Let's think about the following 2 scenarios.
* Container is started.
* Scenario 1) 
    * Somebody "exec" into the container and installs a software in the container using sudo privileges. 
    * Container is being shut down, the newly installed software does not persist, and have to be installed again in the next run. 
* Scenario 2) 
    * Somebody "exec" into the container with `--user 0` parameter, as instructed in the README. He/She has the privileges to install software, for default user to use.
    * Container is shut down, and installed software still does not persist and must be reinstalled.

Now the question is, does the installed software need to persist for the time the container is started again?
* If **NO**, then the above scenario 2 would work.
* If **YES**, then it is better to install the software during the container build process. (This is what I do.)
    * This is also the step, where one would have to implement installing the sudoers, and set up the configurations for the default user to use the sudo.

**Comment by fywu85** [comment]
Thanks for the feedback. 

I think I am more in a third scenario where I want to run a docker container as a virtual machine via a web browser. Most of the time I would like to do things outside of root, such as using jupyter notebook. Some of the time, I would like to install a few things, tweak a few things, through sudo, just to see what happens. 

I am not an expert with Docker but I managed to hack a solution by inserting the following three lines before startup config:
```
RUN adduser --disabled-password --gecos '' --uid 1000 ubuntu
RUN adduser ubuntu sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
```

Perhaps this is not the best practice, but it addressed my original question.
