### ISSUE TITLE
Add GNOME desktop

### ISSUE THREAD

**Issue by darkdragon-001** [ConSol/docker-headless-vnc-container#138]
I found a GNOME on VNC [Dockerfile](https://github.com/darkdragon-001/Dockerfile-Ubuntu-Gnome).

Could you add this as an additional option?

Unfortunately, the full `gnome-session` or `gnome-shell` does not work yet, but many GNOME elements provide a working desktop! See [upstream bug](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1545).

**Comment by darkdragon-001** [comment]
I got it working! The twist was to use `systemd` init system, TigerVNC instead of TightVNC and set `XDG_SESSION_TYPE=x11` in `xstartup`. Check out [my project](https://github.com/darkdragon-001/Dockerfile-Ubuntu-Gnome). Feel free to implement GNOME 3 in your repository!

**Comment by sni** [comment]
thanks for the heads up but we will stick for tightvnc for now.

**Comment by darkdragon-001** [comment]
@sni You **are** already using _TigerVNC_ (see [`src/ubuntu/install/tigervnc.sh`](https://github.com/ConSol/docker-headless-vnc-container/blob/master/src/ubuntu/install/tigervnc.sh))! This was just as a reference for the mentioned Dockerfile in my first post.
