### ISSUE TITLE
How to change port number?

### ISSUE THREAD

**Issue by ghost** [ConSol/docker-headless-vnc-container#150]
I want to setup multiple instances in my machine, but I can not run multiple instances on a single port. Please help me how to change the port number for consol/centos-xfce-vnc. Please help me it's very urgent. I have tried many times but i'm not able to change it.
Thanks

**Comment by iwilder53** [comment]
Line 10 & line 18,19

**Comment by iwilder53** [comment]
Line 10 & line 18 and 19

**Comment by Andy13000ft** [comment]
Can you please share the detail of this solution. I too want to run up multiple instances of the container so users can have a private session. I tried setting environment variables for DISPLAY and NO_VNC_PORT (connecting via a brower) but to no avail...thanks

**Comment by Andy13000ft** [comment]
Apologies, just found the solution in issue#101
