### ISSUE TITLE
issue, how to install a zip unzip, the default extract doesn't work

### ISSUE THREAD

**Issue by xuerake** [ConSol/docker-headless-vnc-container#154]
can't open a zip file.
use default extract here can't work

and can't install the winrar.

sudo apt-get install /headless/downloads/rar.....tar.gz
command not found 
pls help

**Comment by markus-seidl** [comment]
You can add "apt install ..." to the relevant Dockerfile and rebuild the image. I think also passing "--user 0" at the docker run line should work (haven't tried it).
