### ISSUE TITLE
All in these image, chromium pages are always SIGTRAP

### ISSUE THREAD

**Issue by disconnect5852** [ConSol/docker-headless-vnc-container#158]
any

**Tag**

in any image if i open chromium, all pages are "aww snap SIGTRAP"

**Comment by sni** [comment]
Which container is that? Debian? Ubuntu? Centos? Rocky?

**Comment by disconnect5852** [comment]
All of them. Actually i didn't seen any docker images, where chromium not
goes into SIGTRAP, only firefox works.

Sven Nierlein ***@***.***> ezt írta (időpont: 2022. okt. 28.,
P, 20:13):

**Comment by sni** [comment]
adding --disable-dev-shm-usage to the chrome options seems to do the trick.
