### ISSUE TITLE
firefox 52 crashed

### ISSUE THREAD

**Issue by toschneck** [ConSol/docker-headless-vnc-container#16]
Since version 52 is enrolled firefox crash in the `dev` container: 

```
ExceptionHandler::GenerateDump cloned child 99
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Segmentation fault      (core dumped) 
```

=> use older version

**Comment by therealdano** [comment]
I'm running FF 52.02 on Ubuntu 16.04.2 LTS running RealVNC 5.3.1 and XFCE 4.12.1-2. Firefox still crashes with the same error. It doesn't seem to be a docker issue.

**Comment by toschneck** [comment]
@therealdano thx for the info! Hopefully the will fix the issue someday :confounded:
