### ISSUE TITLE
image consol/rocky-xfce-vnc not working on centos-8 or rocky-8 hosts

### ISSUE THREAD

**Issue by btheu** [ConSol/docker-headless-vnc-container#164]
**Image**
consol/rocky-xfce-vnc

**Tag**
latest (id: 720cf510467c)

**Short overview**

When connected, VNC session display a blue screen when running consol/rocky-xfce-vnc from a centos-8 or a rocky-8 distribution.

**Detailed error description**

> cat /etc/redhat-release
> CentOS Linux release 8.4.2105

or

> cat /etc/redhat-release
> Rocky Linux release 8.6 (Green Obsidian)

`docker run --rm -it -p 5901:5901 -p 6901:6901 consol/rocky-xfce-vnc`

The desktop is well displayed when running docker image from centos-7 host.

> cat /etc/redhat-release
> CentOS Linux release 7.9.2009 (Core)

**Additional content**

Inside container logs:

> cat /dockerstartup/wm_startup.log
>
>------------------ startup of Xfce4 window manager ------------------
server does not have extension for -dpms option
xrdb: Cannot allocate memory
xrdb: cannot run '/usr/bin/cpp -P  -DHOST=bd66900b8f4d -DSERVERHOST=bd66900b8f4d -DSRVR_bd66900b8f4d -DDISPLAY_NUM=1 -DCLIENTHOST=bd66900b8f4d -DCLNT_bd66900b8f4d -DVERSION=11 -DREVISION=0 -DVENDOR="The X.Org Foundation" -DVNDR_The_X_Org_Foundation -DRELEASE=12011000 -DNUM_SCREENS=1 -DEXT_GLX -DEXT_XVideo -DEXT_X_Resource -DEXT_Present -DEXT_RECORD -DEXT_DOUBLE_BUFFER -DEXT_MIT_SCREEN_SAVER -DEXT_DAMAGE -DEXT_Composite -DEXT_XINERAMA -DEXT_RANDR -DEXT_RENDER -DEXT_XFIXES -DEXT_XC_MISC -DEXT_XKEYBOARD -DEXT_SYNC -DEXT_BIG_REQUESTS -DEXT_XTEST -DEXT_XInputExtension -DEXT_MIT_SHM -DEXT_SHAPE -DEXT_Generic_Event_Extension -DEXT_VNC_EXTENSION -DSCREEN_NUM=0 -DWIDTH=1280 -DHEIGHT=1024 -DX_RESOLUTION=3776 -DY_RESOLUTION=3779 -DPLANES=24 -DBITS_PER_RGB=8 -DCLASS="TrueColor" -DCLASS_TrueColor=33 -DCOLOR -DCLASS_TrueColor_24=918 -DCLASS_DirectColor_24=1097 -DCLASS_TrueColor_32=77 '
>
>(xfce4-session:57): dbind-WARNING **: 10:06:17.025: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.a11y.Bus received signal 5
>
>(xfce4-session:57): GLib-ERROR **: 10:06:17.025: file ../glib/gthread-posix.c: line 1338 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
/headless/wm_startup.sh: line 13:    57 Trace/breakpoint trap   (core dumped) /usr/bin/startxfce4 --replace > $HOME/wm.log
/usr/bin/startxfce4: X server already running on display :1

**Comment by btheu** [comment]
Closing

docker-ce version was `20.10.6`

upgrading to docker-ce version `20.10.22` fixed the issue

**Comment by sni** [comment]
wouldn't have thought this makes such a difference, but glad it's working now.
