### ISSUE TITLE
VNC not Working

### ISSUE THREAD

**Issue by FearTheWhite** [ConSol/docker-headless-vnc-container#168]
Hi,

if i create a container with your image using
docker run -it -p 5901:5901 -p 6901:6901 -e VNC_PASSWORDLESS=true -d --user 0 --name consol consol/debian-xfce-vnc

i cant connect to it with TightVNC (localhost::5901)

NoVNC is working fine.

is this my error? or a bug?

**Comment by MasakiIchikawa** [comment]
I can't connect with VNC from MacOS
I'm using consol/debian-xfce-vnc

NoVNC is working

**Comment by sni** [comment]
are you using the latest container? There had been an issue fixed in #165

**Comment by MasakiIchikawa** [comment]
Thank you for your reply.

I runned image with refferenced readme.

**docker run -d -p 5901:5901 -p 6901:6901 consol/debian-xfce-vnc**

After your advice, I runned image with this command.

**docker run -d -p 5901:5901 -p 6901:6901 ghcr.io/consol/docker-headless-vnc-container/debian-xfce-vnc:nightly**

Its fine to access with vnc.
Thank you.
