### ISSUE TITLE
Add Ubuntu OS

### ISSUE THREAD

**Issue by Lenny4** [ConSol/docker-headless-vnc-container#171]
Hi

Do you plan to add Ubuntu in addition to Debian and Rocky ?

Like here: https://github.com/fcwu/docker-ubuntu-vnc-desktop

**Comment by sni** [comment]
No, there are no plans to do so. One .deb based and one .rpm based is fine. And without those snap things, debian is easier to maintain. In fact, there was a ubuntu image before, but it
has been migrated to debian with the 2.x release.
