### ISSUE TITLE
ubuntu22.04

### ISSUE THREAD

**Issue by superglg738** [ConSol/docker-headless-vnc-container#179]
ubuntu的镜像太老了，是16版的
能new一个吗？

相同的dockerfile 可以更新否

**Comment by sni** [comment]
please keep issues in english.

**Comment by superglg738** [comment]
the ubuntu's image  is old . it is 16.
can you create a image for ubuntu22.04 ?

**Comment by sni** [comment]
the ubuntu image is deprecated, please use the debian image.
