### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by phpdave11** [ConSol/docker-headless-vnc-container#18]
How do I get root access?  I want to install something after launching the container, but it says I need root access.

When I type `sudo`, it says:

```
sudo: unknown uid 1984: who are you?
```

**Comment by dashesy** [comment]
Either you have to run with `--user 0:0` or just attach to it via another shell:

    docker exec --user 0:0 -ti name_of_docker bash

**Comment by toschneck** [comment]
Hi, sorry for the late answer, I have been on vacation until now.
@dashesy is absolutely  right! 
I added a little documentation for this right now, see: https://github.com/ConSol/docker-headless-vnc-container#hints
