### ISSUE TITLE
no en_US.UTF-8

### ISSUE THREAD

**Issue by superglg738** [ConSol/docker-headless-vnc-container#181]
en_US.UTF-8 don't exist in the debian-xfce-vnc.

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)

ENV LANG='C.UTF-8' LANGUAGE='C.UTF-8' LC_ALL='C.UTF-8'  is rigth

**Comment by sni** [comment]
should be better now, thanks.
