### ISSUE TITLE
Cannot switch to root user vua GUI command line

### ISSUE THREAD

**Issue by pizzaisdavid** [ConSol/docker-headless-vnc-container#184]
**Image**
![cannot_switch](https://github.com/ConSol/docker-headless-vnc-container/assets/4391884/b7f837f1-de0b-4fc2-a04f-773a48b9ad70)

**Tag**

**Short summary**
I am trying to login to root, so I can install things and once I have a good configuration then I would modify my customized Dockerfile. But right now I am struggling to switch to root.

```
/usr/src/app$ su -
Password:
su: Authentication failure
```
I've read that there is no root password, so I just hit enter and that doesn't work.

### How to reproduce
1. run `docker run -p 5901:5901 -p 6901:6901 consol/debian-xfce-vnc`
2. In a browser, open 172.17.0.2:6901/?password=vncpassword
3. Open terminal emulator
4. Run `su root`
5. Press enter for empty password.
6. Failure.

**Comment by sni** [comment]
That's not how it works, see https://github.com/ConSol/docker-headless-vnc-container#1-extend-a-image-with-your-own-software

**Comment by pizzaisdavid** [comment]
Yes, I read that before making a report. Modifying the Dockerfile and rebuilding is a very slow way to debug the things I want to add.
