### ISSUE TITLE
consol/debian-xfce-vnc cannnot to open the portable chromium in terminal

### ISSUE THREAD

**Issue by Bugazelle** [ConSol/docker-headless-vnc-container#191]
Hello @sni 

I found that the consol/debian-xfce-vnc cannot open the portable chromium in terminal
Would you please take just 5 minutes to help me?
Really appreciate for your help in advance.

Here is my try:
1. Download a portable chromium, for example, https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1181205%2Fchrome-linux.zip?generation=1691535836009137&alt=media
2. uzip the file to your current folder
3. run the docker:
```
docker run \
    -e VNC_RESOLUTION=1400x900 \
    -p 6902:6901 \
    -p 5902:5901 \
    -v $(pwd):/tmp  consol/debian-xfce-vnc
```
4. open the: http://127.0.0.1:6902
5. open the terminal, and cd to the chrome-linux, and start the chromium by: `./chrome-wrapper`
here the issue comes: the chromium does not show, and the terminal does not display any error
![chromium_cannot_open_in_terminal](https://github.com/ConSol/docker-headless-vnc-container/assets/44971345/5106aa4f-5565-402c-8eb2-eb2e7ac0bffc)

But the strange thing is: The chromium could work as expected by using the desktop icon
1. Edit the chromium desktop icon execute path: /tmp/demo1/chrome-linux/chrome-wrapper %U
2. Click the desktop icon, the chromium starts!!
![chromium_can_open_from_desktop_icon](https://github.com/ConSol/docker-headless-vnc-container/assets/44971345/181bd53e-19d4-4ba7-bd31-345b7a6aa7f0)

Also, I have used `consol/debian-icewm-vnc`, both the above ways works.

Would you please help me to check why consol/debian-xfce-vnc cannot open the portable chromium in terminal?

Have a nice day to you,
Ken

**Comment by Bugazelle** [comment]
Hi @sni,

Would you please just take 5 minutes to help?
Really appreciate for your help in advance. ;)

Thank you,
Ken

**Comment by Bugazelle** [comment]
fixed

**Comment by sni** [comment]
thanks for the heads up, do you want to share how you solved the issue?
