### ISSUE TITLE
try to build it with VNC_PASSWORDLESS=true as env in the dockerfile

### ISSUE THREAD

**Issue by DannyAtal** [ConSol/docker-headless-vnc-container#192]
**Image**
Debian-xfce
**Tag**
latest
**Short overview**
try to build the image with that env, the Image won't start, I tried to build it from the official docker file and not just from the Image
**Detailed error description**
the container won't start
**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (custom Dockerfiles etc.)

**Comment by DannyAtal** [comment]
any one?

**Comment by DannyAtal** [comment]
@sni maybe you can answer me?

**Comment by sni** [comment]
what's the actual question?

**Comment by DannyAtal** [comment]
When I added the env to the dockerfile and built it the container wont
start and it fails.

בתאריך יום ה׳, 2 בנוב׳ 2023, 21:52, מאת Sven Nierlein ‏<
***@***.***>:

**Comment by DaManDOH** [comment]
I am also left with a non-functioning container when the `VNC_PASSWORDLESS` environment variable is set. The container's log reports as up, but the noVNC port (6901) is unresponsive.

**Comment by bushaev-denis** [comment]
@sni I have simillar behavior as @DaManDOH has.
