### ISSUE TITLE
no graphical interface when login

### ISSUE THREAD

**Issue by alundilong** [ConSol/docker-headless-vnc-container#195]
**Image**
![Screenshot from 2023-12-09 12-53-24](https://github.com/ConSol/docker-headless-vnc-container/assets/24465615/ae3b2763-6d41-496c-9910-537222d6a5d5)

**Tag**
command ran:
sudo docker run -it -p 5901:5901 -p 6901:6901 rockey-xfce-vnc

**Short overview**

**Detailed error description**
No error

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (custom Dockerfiles etc.)
OS: Ubuntu 18.4 LTS
Original Dockefile

**Comment by sni** [comment]
cannot reproduce. I fixed the typos in your command and run:
`docker run -it -p 5901:5901 -p 6901:6901 consol/rocky-xfce-vnc`
works as expected.
You could try to update the image by `docker pull consol/rocky-xfce-vnc`
