### ISSUE TITLE
clipboard not work in vnc and noVNC

### ISSUE THREAD

**Issue by webmalex** [ConSol/docker-headless-vnc-container#21]
consol/ubuntu-icewm-vnc

mac os x / chrome 58

**Comment by toschneck** [comment]
@webmalex so far as i know, clipboard between the vnc-client (your PC) and the vnc-server (docker container) is only possible with native VNC clients. I some VNC clients you have to enable explicitly  this "clipboard sync" feature. Did you try the same with a "normal" VNC server?

**Comment by toschneck** [comment]
@webmalex can I close the issue?
