### ISSUE TITLE
how to change root in cockpit docker manager

### ISSUE THREAD

**Issue by lioliy** [ConSol/docker-headless-vnc-container#26]
It only have these
![B3874EA1-3EE6-427F-8428-757F8BFDD573.png](https://ooo.0o0.ooo/2017/06/28/59536f88bdde4.png)
I can't use docker run -it root 0
Have any other ways to switch to root in cockpit?
PLZ help

**Comment by toschneck** [comment]
I think this is more a question for the cockpit project itself. Normally if you start the container via CLI you will use: `docker run -it --user 0 -p 6911:6901 consol/centos-xfce-vnc`

Alternatively: you can try the old image before wie change to the non-root implementation: `consol/ubuntu-xfce-vnc:1.0.2`

**Comment by lioliy** [comment]
Thanks for help,I use the old image it have worked in cockpit
