### ISSUE TITLE
xterm causes vnc session to stop accepting mouse/keyboard input

### ISSUE THREAD

**Issue by dskyberg** [ConSol/docker-headless-vnc-container#28]
Host: OS X 10.12.5 MacBook Pro
Docker version 17.06.0-ce-rc1, build 7f8486a
Running with docker run -d --rm --name vnc -p 5901:5901 -p 6901:6901 consol/ubuntu-xfce-vnc
Connecting with Screen Sharing to "vnc://localhost:5901

VNC starts up successful.  I can launch chromium, and browse.
Launching UXTerm results in a warning:
uxterm tried unsuccessfully to use local en_US.UTF-8 by setting $LC_CTYPE to "en_US.UTF-8".

![image](https://user-images.githubusercontent.com/11337524/27738874-b977b242-5d7a-11e7-9633-f9d4fd5319d4.png)

Clicking the 'okay' button at the lower left closes the window.  

Launching normal XTerm results in the expected message:
USER_ID: 1984, GROUP_ID: 0
nss_wrapper location: /usr/lib/libnss_wrapper.so

As long as I do not click into the xterm window, everything is fine.  As soon as I do, the VNC session stops accepting mouse/keyboard input at all.

Restarting the VNC session (without restarting the container) succeeds.  The vnc session accepts input again.

Feels like a missing configuration, but I am not familiar enough with X config.  So, not sure where to look.  

Ideas?

**Comment by dskyberg** [comment]
I fixed the initial warning in UXTerm by setting the locale.  I created a Dockerfile.  Running it solved the warning.  But it still stops accepting input as soon as I click in the xterm window.

FROM consol/ubuntu-xfce-vnc
# Perform some extra stuff as root
USER 0
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
# Perform extra stuff as normal user
USER 1984
ENV LANG "en_US.UTF-8"

**Comment by toschneck** [comment]
Thanks for the feedback! I think the problem is, that the locales have been not installed currently, see #27 .
Try to run `RUN locale-gen en_US.UTF-8`

**Comment by dskyberg** [comment]
I updated my Dockerfile with `RUN locale-gen en_US.UTF-8`, but I experience the same problem.  

After some further investigation, this appears to be a problem with VNC client on Mac OS X.  I have not yet seen any steps on the VNC server side to remedy the problem.  So, I am closing this issue.

**Comment by toschneck** [comment]
okay good to know! maybe @simonmeggle can tell you, what vnc client he is using :wink:

**Comment by dskyberg** [comment]
Further justification for closing:  I installed RealVNC client on my mac and re-tested.  XTerm works correctly.  So, it seems the issue is isolated to SOME set of VNC clients on mac - one of which is the native "Screen Sharing" app.

**Comment by toschneck** [comment]
Thx for the sharing!
