### ISSUE TITLE
Preparing for openshift support

### ISSUE THREAD

**Issue by rbo** [ConSol/docker-headless-vnc-container#3]
Adjusting images that they run without modifications in the Open Shift.

**Comment by rbo** [comment]
At branch rbo/openshift (only centos-xfce-vnc) it works, but is not perfect. 
**ToDos:**
 * Cleanup the Dockerfile
 * Adjust ubuntu-xfce-vnc

**Comment by toschneck** [comment]
@rbo maybe the issue with the initializing of the UI environment is relied on the vncserver implementation we use. I had good experiences with `tigervnc` on my pc, where `vnc4server` and `tightvnc` had some problems. I think we should give tigervnc a try :smile: 
> https://github.com/TigerVNC/tigervnc
> Tiger VNC on Ubuntu xenial: http://www.hiroom2.com/2016/05/24/ubuntu-16-04-remote-connect-to-gnome-classic-desktop-with-vnc-xrdp/

**Comment by rbo** [comment]
Added new branch rbo/Issue_#3, all Dockerfiles works in openshift.

**Comment by rbo** [comment]
Update openshift templates & all merged into dev.
