### ISSUE TITLE
About root password

### ISSUE THREAD

**Issue by hzs2004** [ConSol/docker-headless-vnc-container#30]
What is the container's root password?

**Comment by hzs2004** [comment]
bash-4.2$ su
Password:
su: Authentication failure
bash-4.2$

**Comment by hzs2004** [comment]
I tried typing the empty password

**Comment by toschneck** [comment]
There is no root password, you have to start then container as root like described here: https://github.com/ConSol/docker-headless-vnc-container#2-change-user-of-running-sakuli-container

**Comment by NNois** [comment]
Hi,
The docker is started with root user (--user 0).
Installed openssh-server.
Then how can I ssh in ?
```
ssh root@192.168.1.53 -p 6322
root@192.168.1.53's password:
Permission denied, please try again.
```
