### ISSUE TITLE
Container is not executable in host mode

### ISSUE THREAD

**Issue by anil88** [ConSol/docker-headless-vnc-container#41]
The container runs in bridge mode as expected, but can not started in host mode.
The problem is in the vnc_startup.sh script:

`VNC_IP=$(ip addr show eth0 | grep -Po 'inet \K[\d.]+') `

A workaround is to set the VNC_IP=127.0.0.1, but there should be a better solution.

**Comment by toschneck** [comment]
okay I will take look at this

**Comment by toschneck** [comment]
Issue should be already solved since version `1.2.1` - commit https://github.com/ConSol/docker-headless-vnc-container/commit/2e9270355aae2ea813290f7fbce6ffe7ba0677fb #31. If I run `docker run -it -p 6901:6901 -p 5911:5901 --network host consol/ubuntu-xfce-vnc:1.2.1 bash` all is good.

**Comment by anil88** [comment]
The bug fix doesn't work, because the command $(hostname -i) returns multiple interfaces.
This is the output if I start the container in host mode. But I could not connect to 12.12.34.111

------------------ VNC environment started ------------------
VNCSERVER started on DISPLAY= :1
=> connect via VNC viewer with fe80::ba6b:23ff:fe49:bc7c%enp0s25 fe80::42:e3ff:fe19:ab61%docker0 12.12.34.111 172.17.0.1:5901

**Comment by toschneck** [comment]
Can you provide your `docker run` command? Normally I would expect, that you expose the connecting port trough host port mappings like `-p 5901:5901` and then connect via the host:port. The log out put is more like a debug info and not the recommended way to connect. In generell you only should connect/configure  a Docker container trough the provides interfaces of port mappings, volumes and environment variables.

**Comment by anil88** [comment]
This works:
sudo docker run -it -p 6901:6901 -p 5901:5901 consol/centos-xfce-vnc:1.2.2 bash
This doesn't work:
sudo docker run -it -p 6901:6901 -p 5901:5901 --network **host** consol/centos-xfce-vnc:1.2.2 bash

**Comment by toschneck** [comment]
@anil88  Ok, on my workstation, both commands works. What host system do you use?

**Comment by anil88** [comment]
My host system is: CentOS

What do you get when you execute the command : hostname -i

**Comment by toschneck** [comment]
I use Ubuntu, but this should not be a different in my opinion :-/
In docker container:
```
$ docker run -it -p 6901:6901 -p 5901:5901 --network host consol/centos-xfce-vnc:1.2.2 hostname -i
....
------------------ EXECUTE COMMAND ------------------
Executing command: 'hostname -i'
127.0.1.1
```
on host:
```
$ hostname -i
127.0.1.1
```

**Comment by anil88** [comment]
I think this is the problem, you get only one interface. And i get a list of interfaces.
This list will be saved to VNC_IP variable and VNC_IP is then used to start the server.
```
VNC_IP=$(hostname -i)
/launch.sh --vnc $VNC_IP:$VNC_PORT

```
Can be this the problem???

**Comment by toschneck** [comment]
@anil88 that's true. But as long as I can't reproduce it, I can't improve the mechanism. I'm still not sure, if this is really a problem of the implementation or of your docker host setup. Have somebody else the same issue?

Maybe you can develop a solution and propose it as pull request.

**Comment by anil88** [comment]
I have now a solution, but I can not push it to any branch nor can I create a new branch.

**The Problem:**
If you start the vnc-image in host mode and your host has multiple interfaces then it is not possible to start it. Because the command **hostname -i** returns all available interfaces, and in host mode are this the interfaces from the host.
```
VNC_IP=$(hostname -i)
/launch.sh --vnc $VNC_IP:$VNC_PORT
```
the launch.sh file expects only one ip address instead of a list of interfaces.

**Solution:**
start the launch.sh script always with 127.0.0.1. But log all available interfaces...
```
VNC_IP=$(hostname -i)
LOCAL_VNC_IP=127.0.0.1
/launch.sh --vnc $LOCAL_VNC_IP:$VNC_PORT
.....
cho -e "\n\n------------------ VNC environment started ------------------"
echo -e "\nVNCSERVER started on DISPLAY= $DISPLAY \n\t=> connect via VNC viewer with $VNC_IP:$VNC_PORT"
echo -e "\nnoVNC HTML client started:\n\t=> connect via http://$VNC_IP:$NO_VNC_PORT/?password=...\n"
```

I tried it in host and bridge mode and it behaves as expected.

sudo docker run -it --network host consol/centos-xfce-vnc:1.2.2 bash

sudo docker run -it -p 6901:6901 -p 5901:5901 consol/centos-xfce-vnc:1.2.2 bash

**Comment by toschneck** [comment]
@anil88 thx for your solution. I think i can add this, but I have to do some tests before :wink:
