### ISSUE TITLE
Constant Disconnects Through Guacamole

### ISSUE THREAD

**Issue by jason-bean** [ConSol/docker-headless-vnc-container#42]
I've had the same issue with Ubuntu and have not been able to figure out the cause. The error in the Guacamole log seems to indicate an error with the TLS encryption so I would ask for a way to disable requiring encryption to connect. I might fork and attempt to add an option myself to test.

**Comment by toschneck** [comment]
@jason-bean is this Issue placed here correctly? We are using noVNC as HTML5 client :wink:

**Comment by jason-bean** [comment]
Hehe. I would use the noVNC client if this were the only thing I wanted to access remotely. Since I've had this same problem with Ubuntu and Guacamole I think I may just bring this up with them. It seems obvious that there's something that their VNC client implementation isn't doing correctly.
