### ISSUE TITLE
Firefox is unable to install its updates

### ISSUE THREAD

**Issue by srl295** [ConSol/docker-headless-vnc-container#45]
Thanks for this container.  In `ubuntu-xfce-vnc`, Firefox complains that there's an update but it lacks the permissions to perform the update. I'm using this container as a kiosk/meeting room display, and so the message popping up is not helpful.

I can disable automatic updates in Firefox, but could it be helpful to disable the updates in the core image itself?

**Comment by toschneck** [comment]
@srl295 thx for the input. I think we could do this by time. Can you provide a PR for this case?

**Comment by srl295** [comment]
@toschneck sure, i'll give it a look

**Comment by toschneck** [comment]
waiting for @srl295 pr
