### ISSUE TITLE
INST_SCRIPTS and NO_VNC_HOME variables

### ISSUE THREAD

**Issue by michalmiklas** [ConSol/docker-headless-vnc-container#47]
Hi,
I might be wrong but it seems that $HOME variable cannot be defined and also used within the same ENV command. 
I can see that these variables are set to these values:
INST_SCRIPTS=/install 
NO_VNC_HOME=/noVNC

Looking at the file https://github.com/ConSol/docker-headless-vnc-container/blob/master/Dockerfile.centos.xfce.vnc
and 
the details from here:
https://microbadger.com/images/consol/centos-xfce-vnc

I suppose the intention was not to move those two folders out of /headless, correct?

Thanks,

Michal Miklas

**Comment by toschneck** [comment]
Thats correct! Thanks for the hint @michalmiklas !
