### ISSUE TITLE
Port mapping and concurrent containers 

### ISSUE THREAD

**Issue by FreeSpace911** [ConSol/docker-headless-vnc-container#51]
Hello, 
I have created one container with the following command: 
  
`[username@localhost ~]# docker run -d -p 5901:5901 -e VNC_RESOLUTION=1920x1080 -p 6901:6901 consol/ubuntu-xfce-vnc
c6e7194d9ed19f2f291d6cd1925a4352965c37c6692adf2c502e6cf47226a91c
`

And then when I tired to create another container on the same host with different port number I got the following error: 
`[username@localhost ~]# docker run -d -p 5901:5901 -e VNC_RESOLUTION=1920x1080 -p 6902:6902 consol/ubuntu-xfce-vnc
bb77aa923ed98642601049703bfdc8712cc34b2467aa5f235a61c24c41ea3341
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint pedantic_pasteur (1593ca8771edb808e917ee5e60a2a2d07c0e63a8fb8ed38a4d42e50cbf6145a6): Bind for 0.0.0.0:5901 failed: port is already allocated.`

So, what is the right way in order to mange this scenario?
Thanks!

**Comment by plaihonen** [comment]
You have "-p 5901:5901" in both containers.

**Comment by FreeSpace911** [comment]
Hello @plaihonen , 
Changing the 5901 port number will create the container but without connectivity! This is the local VNC port number.

**Comment by plaihonen** [comment]
@FreeSpace911,
You only change the port for the host 0.0.0.0, not for the container.
Per your error message, `Bind for 0.0.0.0:5901 failed: port is already allocated.`, you can not bind the 5901 twice.

See the docker run documentation ( the -p [ ] format )
https://docs.docker.com/engine/reference/run/#expose-incoming-ports

**Comment by toschneck** [comment]
Like already mentioned you have correct your docker port mapping. That's the normal behavior like other docker images would also do. You also can use the `-P` what choose random port:
```
docker run --help
...
     -p, --publish list                   Publish a container's port(s) to the host
     -P, --publish-all                    Publish all exposed ports to random ports`
```
If you wan to have multiple instances with an specific port, just increase your first port number, e.g.:
```
docker run -d -p 5901:5901 -e VNC_RESOLUTION=1920x1080 -p 6901:6901 -d consol/ubuntu-xfce-vnc
docker run -d -p 5902:5901 -e VNC_RESOLUTION=1920x1080 -p 6902:6901 -d consol/ubuntu-xfce-vnc
```
