### ISSUE TITLE
Auto fit the screen resolution

### ISSUE THREAD

**Issue by FreeSpace911** [ConSol/docker-headless-vnc-container#52]
Hello,
Is it possible to fit the Screen resolution to the browser's window size automatically? 
Thanks!

**Comment by toschneck** [comment]
Hi,
for the chromium browser this already implemented, for firefox you can set fullsize over start command, like in this example:
```
docker run -it -p 6901:6901 consol/ubuntu-xfce-vnc firefox  -width 9999 -height 9999 https://labs.consol.de
```
