### ISSUE TITLE
Update noVNC to 1.0.0

### ISSUE THREAD

**Issue by hsiaoyi0504** [ConSol/docker-headless-vnc-container#64]
It looks like noVNC https://github.com/novnc/noVNC has released v1.0.0. Do you consider to update to this version?

**Comment by toschneck** [comment]
@hsiaoyi0504 Thx for the hint! Yeah I think we should upgrade the library to the firsts major release. Currently I don't know, but I take a look at it.
If someone wan't to contribute and send an PR, feel free to do :smiley:

**Comment by hsiaoyi0504** [comment]
I will try to do that.
