### ISSUE TITLE
Sometimes the application bar at the top of xfce4 desktop environment is missing

### ISSUE THREAD

**Issue by hsiaoyi0504** [ConSol/docker-headless-vnc-container#65]
I am not sure it's the problem of this repo or from fundamental dependency and I can't always reproduce this problem.

**Comment by hsiaoyi0504** [comment]
@toschneck I put the log [here](https://gist.github.com/f3b14c0e0d8cc03420c6422c14c0be09).

**Comment by toschneck** [comment]
Can't see more details here ...
