### ISSUE TITLE
Container doesn't work in Reverse Proxy

### ISSUE THREAD

**Issue by misterjtc** [ConSol/docker-headless-vnc-container#67]
This container doesn't appear to work in a reverse proxy. It tries to load but fails to connect and ask for the password.

This is what I see in the log:

172.17.0.1 - - [03/Mar/2018 18:43:51] code 404, message File not found

**Comment by toschneck** [comment]
Like mentioned in #58 a reverse proxy setup has to rely on the [noVNC](https://github.com/novnc/noVNC) implementation. If you get asked for the password, you may not set the http parameter password, like in the example `http://localhost:6901/?password=vncpassword`

**Comment by misterjtc** [comment]
Thanks for the reply!

I found this link for proxy config in the noVNC documentation: https://github.com/novnc/noVNC/wiki/Proxying-with-nginx

I will study this and see if I can find a solution.

**Comment by toschneck** [comment]
Great! Maybe you can document it also in this project?!

**Comment by toschneck** [comment]
@misterjtc any news on this?

**Comment by misterjtc** [comment]
@toschneck I haven't had a chance to look into it but it is on my list.

**Comment by toschneck** [comment]
Ok then I close this issue so far :wink:
