### ISSUE TITLE
Change User

### ISSUE THREAD

**Issue by adi90x** [ConSol/docker-headless-vnc-container#7]
Hello, 

Is there a way to start the container with an user instead of root ? 

Regards,

**Comment by rbo** [comment]
Yes it is, the dev tree should support ```docker run --user $USER``` 

I hope we will release & ship this in 2016.

**Comment by toschneck** [comment]
see #3

**Comment by toschneck** [comment]
@adi90x Until our next release you can use the tagged `:dev` images: `consol/xx-xx-vnc:dev` 
See documentation: https://github.com/ConSol/docker-headless-vnc-container/blob/dev/README.md
