### ISSUE TITLE
Secure Connection

### ISSUE THREAD

**Issue by khwerhahn** [ConSol/docker-headless-vnc-container#70]
Hi, 

It would be amazing, if you could add some infos or even scripts on how to secure (SSL) the connection.

**Comment by toschneck** [comment]
Hi @khwerhahn,
I didn't tried it so far, but  a good starting point for you would be to adjust the startup of the [noVNC]() webserver. Therefore the [launch.sh](https://github.com/novnc/noVNC/blob/master/utils/launch.sh) will be called. This `launch.sh` file contains some options for SSL. 
So maybe you just have to modify this call https://github.com/ConSol/docker-headless-vnc-container/blob/master/src/common/scripts/vnc_startup.sh#L37.

If you have found a solution. Feel free to share it here or via PR :smiley:
