### ISSUE TITLE
Gray screen in Firefox

### ISSUE THREAD

**Issue by ShanshanWei** [ConSol/docker-headless-vnc-container#79]
I got a problem : 
   when running in Firefox for minutes, the screen turns gray, seems like starting up the screensaver. I have to wake it up by moving mouse or the keyboard.
Is this a problem? How can I fix it or setup somewhere if it's not even a problem? Since I want to keep the screen on all the time.

Thanks.

**Comment by toschneck** [comment]
This shouldn't be the case since #11.
@ShanshanWei Which image version/tag do you use?
