### ISSUE TITLE
installing new packages while running as non-root

### ISSUE THREAD

**Issue by pyed** [ConSol/docker-headless-vnc-container#8]
First of all, Thank you for making such useful container!

I started the container as root, then I realized that the app that I want to run requires a non-root user, I added a user via `adduser` but I couldn't get `xface` to switch to it, probably not possible.

I started the container using `--user $(id -u):$(id -g)`, now I'm not root, but I can't install anything, `su` says `Cannot determine your user name`.

**Comment by toschneck** [comment]
Thx I'm glad to hear that you like it!

Currently the latest release didn't support the usermode, but we have already developed it, see #3 .
This changes are already in our `dev` branch.

But until the release, you can use the `dev`-tagged docker image:
`docker run -d -p 5901:5901 -p 6901:6901 --user $(id -u):$(id -g) consol/centos-xfce-vnc:dev` 

If you want to extend the `dev` image you can do it like:
```
#Dockerfile

FROM consol/ubuntu-xfce-vnc:dev
MAINTAINER ...

## use root for install
USER root
RUN apt-get update \
    && apt-get -y install XXX \
    && apt clean
   
## use headless user for run
USER 1984

```

**Comment by rbo** [comment]
Or if you like to test something: you can open a bash as root : 

```shell
$ docker pull consol/centos-xfce-vnc:dev &&  docker run -d -p 5901:5901 -p 6901:6901 --user $(id -u):$(id -g) consol/centos-xfce-vnc:dev
dev: Pulling from consol/centos-xfce-vnc
Digest: sha256:3cc5c972480b480da1bfe5b51566bc77137c91b3a3c19eb0932856581ae68299
Status: Image is up to date for consol/centos-xfce-vnc:dev
17dd34a79bcc8e3f05dd15c5e2cc2d2bf23e9b2bada78b7e573fbc9ff340c23f

$ docker exec -t -i --user 0 17dd34a79bcc8e3f05dd15c5e2cc2d2bf23e9b2bada78b7e573fbc9ff340c23f bash

bash-4.2# yum install telnet
Loaded plugins: fastestmirror, ovl

[..snipped..]

Installed:
  telnet.x86_64 1:0.17-60.el7

Complete!
bash-4.2#
```

Have fun!

**Comment by toschneck** [comment]
`docker run -d -p 5901:5901 -p 6901:6901 --user root consol/centos-xfce-vnc:dev`
Also works for testing with root privileges

**Comment by pyed** [comment]
Thanks a lot for the helpful comments, will try them out when i get home.
