### ISSUE TITLE
[bug] failed to execute child process 'xterm'

### ISSUE THREAD

**Issue by wrfly** [ConSol/docker-headless-vnc-container#82]
![image](https://user-images.githubusercontent.com/7827389/40466574-e12a32a2-5f58-11e8-980e-64fb083659f5.png)

in `consol/ubuntu-xfce-vnc`

via `docker run --rm -ti -e VNC_RESOLUTION=1280x960 -e VNC_PW=pwd -p 6901:6901 --user root consol/ubuntu-xfce-vnc:latest`

**Comment by toschneck** [comment]
I cant reproduce the error with the latest image. It seems that the problem is located to your location. Can you verify that you have the latest image? Maybe try the `dev` image and see if there the issue is still present.

**Comment by wrfly** [comment]
@toschneck Sorry, I pated a wrong command, the problem happened in `consol/ubuntu-xfce-vnc` and the command is 

```
docker run --rm -ti -e VNC_RESOLUTION=1280x960 -e VNC_PW=pwd -p 6901:6901 --user root consol/ubuntu-xfce-vnc:latest
```

**Comment by toschneck** [comment]
@wrfly Ok I checked it but I don't get the error:
![image](https://user-images.githubusercontent.com/4659261/40734957-37913db2-643a-11e8-8495-a3289f07bb1e.png)
Do you try a `docker pull consol/ubuntu-xfce-vnc:latest` before?

**Comment by wrfly** [comment]
I'm trying and will paste another image later~

**Comment by wrfly** [comment]
You can open some shell scripts in HOME folder and see if there is any error

**Comment by wrfly** [comment]
```
consol/ubuntu-xfce-vnc   latest              9a15a1009598        2 months ago        1.15GB
```

Is that hash right?

![image](https://user-images.githubusercontent.com/7827389/40735535-fd739c40-646d-11e8-84e0-9794fd47cc73.png)

**Comment by wrfly** [comment]
@toschneck 

This image has the same issue either:

```
consol/ubuntu-xfce-vnc   dev                 80cdba730007        About an hour ago   1.13GB
```

**Comment by wrfly** [comment]
And can you check this please?

```txt
➜  ~ docker run --rm -ti -e VNC_RESOLUTION=1280x960 -e VNC_PW=pwd -p 6901:6901 --user root consol/centos-icewm-vnc:latest
USER_ID: 0, GROUP_ID: 0

------------------ update chromium-browser.init ------------------

... set window size 1280 x 960 as chrome window size!


------------------ change VNC password  ------------------

------------------ start noVNC  ----------------------------

------------------ start VNC server ------------------------
remove old vnc locks to be a reattachable container
start vncserver with param: VNC_COL_DEPTH=24, VNC_RESOLUTION=1280x960
...
➜  ~ docker run --rm -ti -e VNC_RESOLUTION=1280x960 -e VNC_PW=pwd -p 6901:6901 consol/centos-icewm-vnc:latest     
USER_ID: 1000, GROUP_ID: 0
nss_wrapper location: /usr/lib64/libnss_wrapper.so

------------------ update chromium-browser.init ------------------

... set window size 1280 x 960 as chrome window size!


------------------ change VNC password  ------------------

------------------ start noVNC  ----------------------------

------------------ start VNC server ------------------------
remove old vnc locks to be a reattachable container
no locks present
start vncserver with param: VNC_COL_DEPTH=24, VNC_RESOLUTION=1280x960
...
➜  ~ 
```

It just cannot start

**Comment by wrfly** [comment]
Hello bro @toschneck , actually you don't have to install a new xterm, link it is OK, I tested it. See https://github.com/ConSol/docker-headless-vnc-container/pull/83

And perhaps you can commit another to add the Chinese front, thanks~

**Comment by toschneck** [comment]
@wrfly will do soon, have to check how big the packages are in #83 :wink:
