### ISSUE TITLE
Password can not be changed after docker commit.

### ISSUE THREAD

**Issue by OlegJakushkin** [ConSol/docker-headless-vnc-container#88]
Simptoms:
One can start a docker commited container image with another password, yet on login mouse does not move, if old pass is inserted login is sucsessful and mouse moves correctly

Steps to reproduce:
 - Create, start image with password like ScPa$$W0rd@a6
`docker run -d -p 15000:6901  -e VNC_PW=ScPa$$W0rd@a6 --user 0 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined oj/td:latest`
 - Loginto it, install software\do stuff
 - Docker commit that container (say `oj/td:latest`)
 - Try to start the commited one with a new password
`docker run -d -p 15001:6901  -e VNC_PW=Blas$word --user 0 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined oj/td:latest`

**Comment by toschneck** [comment]
Doing a `docker commit` is  not really good practice, so please write a `Dockerfile` for your purpose: https://github.com/ConSol/docker-headless-vnc-container#1-extend-a-image-with-your-own-software

**Comment by OlegJakushkin** [comment]
There are so many cases when it is the only reasonably fast option that it really is:
Workflow for me is quite simple:
1) prepare base environment (in the docker file)
2) prepare visual environment (with Descktop icons, ubuntu configurations etc)
3) commit it and replicate for students to study in (with user 0 for them to be capable to learn ubuntu\coding)
4) Say a student has radically changed environment (installed other DNN environment, generated ton of new config files) - we want to save his work and probably it will be the base image for the future so we commit it. Or we want to save\fork\inspect his work.
5) We redeploy it - and we really need a mechanics to change a password.

So please at least tell us where to look into for password to be changeable.

**Comment by s1hofmann** [comment]
@OlegJakushkin Were you able to resolve your issue?

**Comment by OlegJakushkin** [comment]
Well we used a single old-password, one for all students so it is not at all a general solution...
btw only like first 8 letters of it were used, from 'ScientificPaSSWOrd@apmath777` only `ScientificPa` was really required...

**Comment by s1hofmann** [comment]
TigerVNCs `vncpasswd` only uses the first eight characters of a password, as mentioned in [the docs](http://tigervnc.org/doc/vncpasswd.html).

Regarding your password, as already mentioned, our headless containers are not designed to be used the way you're doing it. Since your `docker commit` workflow is rather special, I'd indeed recommend to create your own custom image.

**Comment by toschneck** [comment]
@s1hofmann maybe we just have to delete `.vnc/passwd` file and then password would set on every startup fresh and also after commit :thinking: 
https://github.com/ConSol/docker-headless-vnc-container/blob/3ec0a2407cb44bb41907266b741c065a7c9706ba/src/common/scripts/vnc_startup.sh#L69
And @OlegJakushkin  yeah the password length is an issue by vnc itself, so we can't do there something
