### ISSUE TITLE
many x apps fail (solution included)

### ISSUE THREAD

**Issue by idjohnson** [ConSol/docker-headless-vnc-container#89]
First, love this container. awesome work. thank you (solving my locked down laptop issues for development).

I found many apps (e.g. atom) would vomit with "Gtk-WARNING **: cannot open display:"
Trying various DISPLAY exports did not help.

What did sort it out was (as root)
**yum groupinstall "X Window System"**

Now x apps (like atom editor) launch just fine from prompt.  still unsure what specifically was missing, but it solved it, no reboot required.

**Comment by s1hofmann** [comment]
Can you provide some details on your setup?

Which applications are causing errors and how did you install and run e.g. Atom?
Which image are you running?

**Comment by s1hofmann** [comment]
Due to inactivity, I'll close this issue.
