### ISSUE TITLE
Does this run on the cloud?

### ISSUE THREAD

**Issue by mgahan** [ConSol/docker-headless-vnc-container#91]
First of all, this is an awesome image. I have been able to get it to work pretty well on my desktop, but I have had some trouble getting it to work on Google Cloud Platform. I have opened up ports 5901 and 6901 and I am running this:

```
docker run -d -p 5901:5901 -p 6901:6901 -e VNC_RESOLUTION=1920x810 consol/ubuntu-xfce-vnc
```

Any ideas what the disconnect is? Thanks for all the help

I am creating the container on the following image:

Container-Optimized OS 65-10323.94.0 stable
Kernel: ChromiumOS-4.4.111 Kubernetes: 1.8.7 Docker: 17.03.2

**Comment by s1hofmann** [comment]
> Any ideas what the disconnect is?

Could you elaborate a bit more on this? Maybe provide some log output regarding the disconnect?

**Comment by toschneck** [comment]
@mgahan you can deploy it on GCP through Kubernetes and public load balancer with this template: https://github.com/ConSol/docker-headless-vnc-container/blob/master/kubernetes/kubernetes.headless-vnc.example.deployment.yaml
There you may have to change the service type and ports for external access

**Comment by mgahan** [comment]
I am not really getting an error message. I just get "Page not found" when I navigate to the external ip with the port (I changed the firewall rules to allow 5901 and 6901).

**Comment by toschneck** [comment]
ok so in my opinion the issue was was not related to our image I think.
