### ISSUE TITLE
Want to root privilege in docker 

### ISSUE THREAD

**Issue by DineshGuptaa** [ConSol/docker-headless-vnc-container#92]
Hi All,

I have installed the docker container -ubuntu xfce vnc- but not unable to execute the sudo commod inside the docker container as I am able to do.
Please help me to get the sudo privilege in ubunto xfce vnc.
Also, how may I modify the Sakuli background from the Firefox & can I avoid using nss wrapper. 

Thanks
Dinesh

**Comment by s1hofmann** [comment]
You can simply switch to the `root` account by adding the `--user` flag to your Docker run command.
E.g. `docker run -it -p 5901:5901 -p 6901:6901 --user 0 consol/ubuntu-xfce-vnc`

When running as root user, `libnss_wrapper` is also not configured for pre-loading.

**Comment by toschneck** [comment]
You can also get sudo on a running container when you use the `exec` command:
`docker exec -it -u 0 <id> bash`

**Comment by DineshGuptaa** [comment]
Thanks for the solution
