### ISSUE TITLE
Don't want to use NSS wrapper

### ISSUE THREAD

**Issue by DineshGuptaa** [ConSol/docker-headless-vnc-container#93]
Hi,

Is there any way to avoid nss_wrapper, It is giving me an error in Ubuntu 14.04.
    `E: Unable to locate package libnss-wrapper 
     The command '/bin/sh -c $INST_SCRIPTS/libnss_wrapper.sh' returned a non-zero code: 100`

Please help me.

Regards,
Dinesh

**Comment by toschneck** [comment]
@DineshGuptaa we don't use Ubuntu 14 in our container. What image do you use? How do you start it?

**Comment by DineshGuptaa** [comment]
Hi Toschneck,
I made changes in the Docker.ubuntu.xfce.vnc. Also, I tried with 16.04 but voice is not coming. Youtube run without voice. 
If you may help on the same will be great.

Thanks, 
Dinesh Gupta

**Comment by s1hofmann** [comment]
Are you trying to get audio output for a container?

> I tried with 16.04 but voice is not coming

In order to get audio output in a Docker container,  you'd have to add your hosts audio device to the container via `docker run --device <device> ...`

See https://stackoverflow.com/a/41084959/5132595

**Comment by rahulhada** [comment]
base 18.04 worked for me
