### ISSUE TITLE
Persistence between restarts

### ISSUE THREAD

**Issue by bwelsher** [ConSol/docker-headless-vnc-container#95]
Hi, I really like the setup of the container but it would be useful for me for it to retain settings etc between restarts. Is this behavior by design or is it a feature that could incorporated in future?
Thanks!

**Comment by s1hofmann** [comment]
You could try to use a Docker volume to persist $HOME, where most of your configs should be stored.
E.g.:

`docker run --rm -d -p 5901:5901 -p 6901:6901 -v home:/headless --user 0 consol/ubuntu-xfce-vnc`

**Comment by bwelsher** [comment]
Thanks for getting back to me. I'm afraid my technical knowledge of containers is rather basic, I just use them through unraid currently. I don't know if I'm able to alter the run command that unraid passes but can look into it.

**Comment by s1hofmann** [comment]
Have you been able to resolve your issue?

**Comment by bwelsher** [comment]
Hi, so it seems I can pass extra parameters when the container is run. So in this scenario I think I just need to specify a location for 'home'. I guess that would be done with the '-v home:/headless' element of the command you gave me?

**Comment by s1hofmann** [comment]
Correct. `-v` specifies a Docker volume named `home`, which would persist data stored in folder `/headless`, which is the containers `$HOME`.

**Comment by bwelsher** [comment]
OK, so I am using the extra parameter `-v appdata:/headless` to start the container where `appdata` is a share on the local file system. This makes the container persist between restarts though I cannot see any files being created in `/appdata`. So it's working but I am just not sure how!

**Comment by s1hofmann** [comment]
Your data is persisted using a [Docker volume](https://docs.docker.com/storage/volumes/).
In order to see persistet data, you'd have to check the volume's mountpoint:
```
docker volume inspect appdata
```
Output:
```
[
    {
        ...
        "Mountpoint": "<path>", <-- Your data is persistet here
        "Name": "home",
        ...
    }
]
```

> So it's working but I am just not sure how!

So I'll close this issue.
