### ISSUE TITLE
Support Ubuntu 18.04 container

### ISSUE THREAD

**Issue by bofortitude** [ConSol/docker-headless-vnc-container#96]
Hi, as the Ubuntu 18.04 has been released for about half year, could you please make a container base on Ubuntu 18.04?

**Comment by bertram1isu** [comment]
@bofortitude , I found that just replacing 16.04 with 18.04 in the FROM line seems to be all that is required.    So far I haven't run into any issues with the resulting image.

**Comment by bofortitude** [comment]
Really, thanks, i’ll have a try

**Comment by sam2kb** [comment]
There's a fork for Ubuntu 18.04
https://hub.docker.com/r/wittyfinch/ubuntu-vnc

**Comment by DRepinSLB** [comment]
It would be great to have both Ubuntu 16.04 and Ubuntu 18.04 officially supported.

**Comment by Felix-neko** [comment]
Please support 18.04 officially, it would be really great!

**Comment by horrorschau105** [comment]
For Ubuntu 20.04, the above trick won't work, because the `/headless/noVNC/utils/launch.sh`script is lacking a python2 interpreter and will fail.

To fix it, it's (for example) sufficient to link to python interpreter in the Dockerfile:
```Dockerfile
RUN ln -s `which python2` /usr/bin/python
```

**Comment by tmyoda** [comment]
There is also a fork for Ubuntu 18.04.
https://hub.docker.com/r/tmyoda/ubuntu18-xfce-vnc
https://hub.docker.com/r/tmyoda/ubuntu18-icewm-vnc

I just forked this repository and updated it to 18.04. I've changed anything else.
